- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  startingGear: JanitorGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Janitor
  - Maintenance
# Desativado at√© criarmos um feriado equivalente
#   special:
#   - !type:GiveItemOnHolidaySpecial
#     holiday: GarbageDay
#     prototype: WeaponRevolverInspector

- type: startingGear
  id: JanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
<<<<<<< HEAD
=======
  innerClothingSkirt: ClothingUniformJumpskirtJanitor
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    id: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
<<<<<<< HEAD
=======
  innerClothingSkirt: ClothingUniformJumpskirtJanimaid
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
